//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApplication.Common
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BaseMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVA.Common.BaseMessages", typeof(BaseMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved successfully.
        /// </summary>
        internal static string Common_DataSaveMsg {
            get {
                return ResourceManager.GetString("Common_DataSaveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model is null..
        /// </summary>
        internal static string Common_ErrorMsg_ModelNull {
            get {
                return ResourceManager.GetString("Common_ErrorMsg_ModelNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save operation failed.
        /// </summary>
        internal static string Err_DataSaveFailed {
            get {
                return ResourceManager.GetString("Err_DataSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Opportunity.
        /// </summary>
        internal static string Err_InvalidOpportunity {
            get {
                return ResourceManager.GetString("Err_InvalidOpportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name is already exists..
        /// </summary>
        internal static string Err_ORG_AlreadyExist {
            get {
                return ResourceManager.GetString("Err_ORG_AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database not created..
        /// </summary>
        internal static string Err_ORG_DatabaseNotCreated {
            get {
                return ResourceManager.GetString("Err_ORG_DatabaseNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name already exists. Choose a different database name..
        /// </summary>
        internal static string Err_ORG_DbAlreadyExist {
            get {
                return ResourceManager.GetString("Err_ORG_DbAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not inserted in entity table..
        /// </summary>
        internal static string Err_ORG_EntityRecordNotInserted {
            get {
                return ResourceManager.GetString("Err_ORG_EntityRecordNotInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMS Organization create fail.
        /// </summary>
        internal static string Err_ORG_ImsOrgFail {
            get {
                return ResourceManager.GetString("Err_ORG_ImsOrgFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Header Column Number Already Exist..
        /// </summary>
        internal static string Msg_HdrColumnNameAlreadyExist {
            get {
                return ResourceManager.GetString("Msg_HdrColumnNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Header Name Already Exist..
        /// </summary>
        internal static string Msg_HdrNameAlreadyExist {
            get {
                return ResourceManager.GetString("Msg_HdrNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database created sucessfully..
        /// </summary>
        internal static string Msg_ORG_DatabaseCreated {
            get {
                return ResourceManager.GetString("Msg_ORG_DatabaseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data deleted successfully.
        /// </summary>
        internal static string Msg_ORG_Deleted {
            get {
                return ResourceManager.GetString("Msg_ORG_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio created successfully..
        /// </summary>
        internal static string Msg_ORG_PortfolioInserted {
            get {
                return ResourceManager.GetString("Msg_ORG_PortfolioInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharding map with database.
        /// </summary>
        internal static string Msg_ORG_ShardingDbMapped {
            get {
                return ResourceManager.GetString("Msg_ORG_ShardingDbMapped", resourceCulture);
            }
        }
    }
}
